name: Publish And Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@master
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          connect_timeout: 10s
          first_ssh: |
            rm -rf /root/ai-tools-srv/*
          scp: |
            './*' => /root/ai-tools-srv/
          last_ssh: |
            export OPENAI_API_KEY=$OPENAI_API_KEY
            cd /root/ai-tools-srv
            chmod +x deploy.sh
            ./deploy.sh
